apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: frontend-ingress
    namespace:  dev
spec:
    rules:
    - http:
        paths:
        - path: /api
          backend:
            serviceName: hello-service
            servicePort: 80
