apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-echo1
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
spec:
  tls:
  - hosts:
    - testsite2.domain.io
  rules:
  - host: testsite2.domain.io
    http:
      paths:
      - backend:
          serviceName: echo1
          servicePort: 80
