  
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-echo1
spec:
  rules:
  - host: testsite2.domain.io
    http:
      paths:
      - backend:
          serviceName: echo1
          servicePort: 80
