apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-echo1
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: echo1
          servicePort: 80
