apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mysample-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: 52.250.106.238
    http:
      paths:
      - path: /
        backend:
          serviceName: mysample-service
          servicePort: 80
