apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mysample-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
   - http:
      paths:
      - path: /
        backend:
          serviceName: mysample-service
          servicePort: 80
